#! /usr/bin/env bash
###############################################################################
# Script to background a hyaklink connection.
# Uses ssh to connect to the remote host and open forwarded ports, but don't
# open a screen session or foreground the ssh.


# Configuration ===============================================================

# Load the hyaklink-init script.
THISSCRIPT="$(command -v "${BASH_SOURCE[0]}")"
THISDIR="$(dirname "${THISSCRIPT}")"
source "${THISDIR}/hyaklink-init"

# The help / syntax function.
function HELP {
    less <<EOF
Syntax: hyaklink-open [--config-dir=<DIR>] <LINK-NAME>

The hyaklink-open subcommand attaches a previously created hyaklink (node) to
the current session using ssh but, unlike the hyaklink-fg command, does not
open screen and instead starts the ssh client in daemon mode. The purpose of
the command is to open any ports specified by the link; such ports are
automatically closed when the user logs out or can be closed using the
hyaklink-close command. The following option is available:

  --config-dir <directory> | --config-dir=<directory>
  If one wishes to use a specific directory for storing hyaklink connection
  metadata, provide it via this option. The default configuration directory is
  $HOME/.hyak/hyaklink
EOF
}

# We only allow a single tag to be set by command line; we give this variable
# a value once it's been found in the argument list.
TAG_SET=""


# Arguments ===================================================================

# Check for arguments we specifically take.
while [ $# -gt 0 ]
do case "$1"
   in # Config-dir has already been removed, so anything else is a tag.
      *)
          if [ -z "${TAG_SET}" ]
          then TAG="$1"
               TAG_SET=yes
          else echo "Invalid argument: $1" 1>&2
               exit 1
          fi
          ;;
   esac
   shift
done

# At this point, if we haven't been given a job name, we create a random name
# then rename the job once it's been created. However, we might have been given
# A TAG or an SBATCH_JOB_NAME or both.
if [ -z "${TAG}" ]
then echo "No hyaklink tag was given; syntax: hyaklink-open <link-id>" 1>&2
     exit 1
fi
export TAG

# We need to prepare to save the node metadata in the ~/.hyak/hyaklink
# configuration directory.  First make sure the directory exists.
if ! [ -d "${HYAKLINK_CONFIG_DIR}" ]
then echo "Attempting to connect hyaklink using nonexistant config dir:" 1>&2
     echo "${HYAKLINK_CONFIG_DIR}" 1>&2
     exit 1
fi
# This is the file we'll use.
ENVFILE="${HYAKLINK_CONFIG_DIR}/${TAG}.env"
if ! [ -r "${ENVFILE}" ]
then echo "No hyaklink file found for tag ${TAG} (${ENVFILE})" 1>&2
     exit 1
fi
source "${ENVFILE}"


# Connect to Node =============================================================

# First we need to generate the list of port-forwarding arguments.
PORTARGS=()
for port in "${HYAKLINK_PORTS[@]}"
do PORTARGS+=("-L${port%:*}:localhost:${port%*:}")
done

# We need to create a control socket so we can kill this later.
SOCKFILE="${HYAKLINK_SOCKET_DIR}/${TAG}.sock"

# We can start the ssh process in the background now.
ssh -M -S "${SOCKFILE}" -f -N -o ExitOnForwardFailure=yes \
    "${PORTARGS[@]}" \
    "${SLURM_HOSTNAME}"

# Assuming that worked, all is well!
exit $?
